// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetApiEntraUserByIdData, GetApiEntraUserByIdError, GetApiEntraUserByIdResponse, GetApiEntraUserAllData, GetApiEntraUserAllError, GetApiEntraUserAllResponse, GetApiEntraUserFilterData, GetApiEntraUserFilterError, GetApiEntraUserFilterResponse } from './types.gen';

export const client = createClient(createConfig());

export class V1Service {
    public static getApiEntraUserById<ThrowOnError extends boolean = false>(options: Options<GetApiEntraUserByIdData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiEntraUserByIdResponse, GetApiEntraUserByIdError, ThrowOnError>({
            ...options,
            url: '/api/entra/user/{id}'
        });
    }
    
    public static getApiEntraUserAll<ThrowOnError extends boolean = false>(options?: Options<GetApiEntraUserAllData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiEntraUserAllResponse, GetApiEntraUserAllError, ThrowOnError>({
            ...options,
            url: '/api/entra/user/all'
        });
    }
    
    public static getApiEntraUserFilter<ThrowOnError extends boolean = false>(options?: Options<GetApiEntraUserFilterData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiEntraUserFilterResponse, GetApiEntraUserFilterError, ThrowOnError>({
            ...options,
            url: '/api/entra/user/filter'
        });
    }
    
}