// This file is auto-generated by @hey-api/openapi-ts

export type PagedUserResponseModel = {
    total: number;
    items: Array<(UserResponseModel)>;
};

export type ProblemDetails = {
    type?: (string) | null;
    title?: (string) | null;
    status?: (number) | null;
    detail?: (string) | null;
    instance?: (string) | null;
    [key: string]: (unknown | string | number) | undefined;
};

export type UserResponseModel = {
    key: string;
    displayName: string;
    email?: (string) | null;
};

export type GetApiEntraUserByIdData = {
    path: {
        id: string;
    };
};

export type GetApiEntraUserByIdResponse = ((UserResponseModel));

export type GetApiEntraUserByIdError = ((ProblemDetails));

export type GetApiEntraUserAllData = {
    query?: {
        skip?: number;
        take?: number;
    };
};

export type GetApiEntraUserAllResponse = ((PagedUserResponseModel));

export type GetApiEntraUserAllError = ((ProblemDetails));

export type GetApiEntraUserFilterData = {
    query?: {
        filter?: string;
    };
};

export type GetApiEntraUserFilterResponse = (unknown);

export type GetApiEntraUserFilterError = unknown;